tum_aileler = {
    "Vesper Duo Brushed Gold",
    "Vesper Duo Brushed Silver",
    "Vesper Quattro Brushed Gold",
    "Vesper Quattro Brushed Silver",
    "Orion Gold",
    "Orion Gold",
    "Orion Gold",
    "Orion Gold",
    "Orion Gunmetal",
    "Orion Gunmetal",
    "Orion Gunmetal",
    "Orion Gunmetal",
    "Ring Light Polished Gold",
    "Crescent Light",
    "Crescent Table Lamp",
    "Mini Crescent Light",
    "Mini Crescent Table Lamp",
    "Mini Crescent Chandelier 3 Piece",
    "Mini Crescent Chandelier 5 Piece",
    "Mini Crescent Ceiling Light",
    "Hail 3 Light Short, Brushed Gold",
    "Hail 3 Light Short, Brushed Silver",
    "Hail 3-piece Chandelier, Brushed Gold",
    "Hail 3-piece Chandelier, Brushed Silver",
    "Hail 3 Light Tall, Brushed Gold",
    "Hail 3 Light Tall, Brushed Silver",
    "Hail 6 Light Tall, Brushed Gold",
    "Hail 6 Light Tall, Brushed Silver",
    "Pantheum Surface Light",
    "Altar Wall Light",
    "Altar 4 Light Short",
    "Altar 4 Light Tall",
    "Aurora Ring 1 (20)",
    "Aurora Ring 2 (32)",
    "Aurora Ring 3 (45)",
    "Aurora Ring 4 (60)",
    "Aurora Ring 5 (72)",
    "Aurora 2 Tier XXL Chandelier",
    "Aurora 3 Tier Large Chandelier",
    "Aurora 3 Tier XXL Chandelier",
    "Carousel Polished Gold",
    "Carousel Polished Chrome",
    "Carousel Polished Gunmetal",
    "Carousel Matte Black",
    "Carousel Medium Polished Gold",
    "Carousel Medium Polished Chrome",
    "Carousel Medium Polished Gunmetal",
    "Carousel Medium Matte Black",
    "Carousel Large Polished Gold",
    "Carousel Large Polished Chrome",
    "Carousel Large Polished Gunmetal",
    "Carousel Large Matte Black",
    "Carousel XL Polished Gold",
    "Carousel XL Polished Chrome",
    "Carousel XL Polished Gunmetal",
    "Carousel XL Matte Black",
    "Requiem Ring",
    "Requiem Globe",
    "Requiem Sphere",
    "Requiem Tube",
    "Chant Surface Light Clear",
    "Chant 4x4 Chandelier",
    "Chant 6x6 Chandelier",
    "Chant 6x6 2-Tier Chandelier",
    "Chamber Light Small",
    "Chamber Light Large",
    "Chamber Chandelier 3 Piece",
    "Chamber Chandelier 5 Piece",
    "Crystal Tube Light Brass",
    "Eclipse Pendant Gold",
    "Eclipse Chandelier Gold",
    "Eclipse Table Lamp Gold",
    "Crystal Tube Wall Light Brass",
    "Eclipse Pendant Chrome",
    "Eclipse Chandelier Chrome",
    "Eclipse Table Lamp Chrome",
    "Crystal Tube Wall Light Chrome",
    "Fulcrum Light Polished Gold",
    "Fulcrum Light Polished Chrome",
    "Fulcrum Light Matte Black",
    "Tube Light Brass",
    "Fulcrum Chandelier 3 Piece Polished Gold",
    "Fulcrum Chandelier 3 Piece Polished Chrome",
    "Fulcrum Chandelier 3 Piece Matte Black",
    "Tube Wall Light Brass",
    "Fulcrum Chandelier 5 Piece Polished Gold",
    "Fulcrum Chandelier 5 Piece Polished Chrome",
    "Fulcrum Chandelier 5 Piece Matte Black",
    "Tube Wall Light Chrome",
    "Acid Marble Table Lamp",
    "Little Lens Flair Pendant Brass",
    "Little Lens Flair Chandelier Brass",
    "Little Lens Flair Table Lamp Brass",
    "Lens Flair Pendant Brass",
    "Lens Flair Table Lamp Brass",
    "Lens Flair Pendant Black",
    "Lens Flair Table Lamp Black",
    "Crystal Bulb Table Lamp Clear",
    "Clear Crystal Bulb & Pendant Brushed Brass",
    "Clear Crystal Bulb & Pendant Polished Chrome",
    "Clear Crystal Bulb Chandelier 3 Piece Brushed Brass",
    "Clear Crystal Bulb Chandelier 5 Piece Brushed Brass",
    "Clear Crystal Bulb Chandelier 3 Piece Polished Chrome",
    "Clear Crystal Bulb Chandelier 5 Piece Polished Chrome",
    "Crystal Bulb Wall Light Clear",
    "Crystal Bulb Clear",
    "Crystal Bulb Ceiling Light Clear",
    "Decanterlight Square",
    "Decanterlight Bell",
    "Decanterlight Tulip",
    "Decanterlight Classic Cut Chandelier 3 Piece",
    "Decanterlight Classic Cut Chandelier 5 Piece"
}