aileler = [
    'Aaro',
    'Armen', 
    'Biny',           
    'Collection Atmospherics',
    'Collection Cauvet',
    'Collection Cordless',
    'Collection Eric de Dormael',
    'Collection Outdoor',
    'Focus',
    'Here Comes the Sun',
    'In The Sun',
    'In The Tube',
    'ISP',
    'La Lampe B',
    'La Lampe Frechin',
    'Lampe Gras',
    'Les Acrobates de Gras',
    'Les Doubles de Gras',
    'Light Me Tender',
    'Mantis',
    'MbE',
    'Mono',
    'NL12',
    'Niwaki',
    'Org',
    'Plume',
    'Poudrier',
    'Respiro',
    'SOUL',
    'Tell Me Stories',
    'Tobo',
    'VVV',
    'Vision 20/20',
    'Yasuke'
]
aileler_asil = [
    'Biny',
    'In The Tube',
    'Lampe Gras',
    'SOUL',
]

aileler_ayni = [
    'Biny Floor',
    'In The Tube 360°',
    'Lampe Gras Outdoor',
    'SOUL Outdoor',
]
