aileler = [
    'Aaro',
    'Armen',
    'Biny',
    'Biny Floor',
    'Collection Atmospherics',
    'Collection Cauvet',
    'Collection Cordless',
    'Collection Eric de Dormael',
    'Collection Outdoor',
    'Focus',
    'Here Comes the Sun',
    'In The Sun',
    'In The Tube',
    'In The Tube 360°',
    'ISP',
    'La Lampe B',
    'La Lampe Frechin',
    'Lampe Gras',
    'Lampe Gras Outdoor',
    'Les Acrobates de Gras',
    'Les Doubles de Gras',
    'Light Me Tender',
    'Mantis',
    'MbE',
    'Mono',
    'NL12',
    'Niwaki',
    'Org',
    'Plume',
    'Poudrier',
    'Respiro',
    'SOUL',
    'SOUL Outdoor',
    'Tell Me Stories',
    'Tobo',
    'V V V',
    'Vision 20/20',
    'Yasuke'
]
aileler_ayni = [
    'Biny',
    'In The Tube',
    'Lampe Gras',
]